### ISSUE TITLE
OpenSSL.tsafe is deprecated

### ISSUE THREAD

**Issue by strichter** [cdent/paste#15]
The `OpenSSL.tsafe` module has been deprecated. `OpenSSL.tsafe.Connection` now simply points to `OpenSSL.SSL.Connection`.

`OpenSSL.tsafe` is used in `httpserver.py`.

**Comment by cdent** [comment]
Thanks, if you're able to provide a pull request with the change that would be great. Otherwise I'll try to get around to tuning this up in the near future.

**Comment by strichter** [comment]
@cdent Done, see #16

**Comment by cdent** [comment]
Closed by #16, released as 3.0.5
