### ISSUE TITLE
changelog not found in standard locations

### ISSUE THREAD

**Issue by sunew** [cdent/paste#24]
There should be a CHANGELOG or similar in the docs or in the root

**Comment by cdent** [comment]
If you'd like to fix this, a patch would be warmly welcomed.

If that doesn't happen, though, then it is unlikely this will be fixed. From the README:

> Paste is in maintenance mode and recently moved from bitbucket to github. Patches are accepted to keep it on life support, but for the most part, please consider using other options.

There are _many_ things in paste which are non-standard and while it is useful to fix bugs I'm not sure fixing those non-standard things is worth the effort.

The changelog is in the docs, named [news](https://pythonpaste.readthedocs.io/en/latest/news.html).

**Comment by sunew** [comment]
@cdent thanks for the quick reply:) 
If i change the location/name it will break other things I assume, such as the docs?

Agree about the effort vs maintenance mode. 

(Context: Was looking into the possible problems of upgrading a range of dependencies of an existing project)
