### ISSUE TITLE
Question about "from paste.deploy import loadapp"

### ISSUE THREAD

**Issue by 4383** [cdent/paste#25]
Hello

I've some questions concerning this code [`from paste.deploy import loadapp`](https://github.com/cdent/paste/blob/5a542da992618e30a508f7f03259f63cf2ee1ceb/paste/modpython.py#L59)

I can't find any `deploy` module in [the source code of `paste`](https://github.com/cdent/paste/search?q=deploy&unscoped_q=deploy), also I don't find any entry_points or things like that related to `deploy` your `setup.py` or no dynamic definition of it in the `__init__.py` mechanismes....

Maybe I missing something... so... can you indicate to me where I can find the `deploy` module and the `loadapp` function, and also explain how you load this module and the black magic behind that.

Do not hesitate to ask me questions if needed.

I waiting for your reply.

Thanks by advance for your help and your time :)

**Comment by cdent** [comment]
Heh, yeah, it is pretty weird and hard to figure out. This is one the things that predates my time maintaining paste. Basically at some point in the past people realized that `paste.deploy` was one of the main useful parts of paste and they didn't want all the rest of paste, so it was extracted. As paste and paste.deploy both got "old" maintenance sort of diverged. They are still maintained, but as separate packages.

paste.deploy is under the domain of the Pylons project (and I'm a maintainer of it over there too): https://github.com/Pylons/pastedeploy and https://pypi.org/project/PasteDeploy/ 

If that covers it, feel free to close this. If not, let me know how else I can help.

**Comment by 4383** [comment]
@cdent excellent! fair enough.

I'll close it now.

thanks for the free guided tour :)
