### ISSUE TITLE
base64.encodestring deprecation warning

### ISSUE THREAD

**Issue by tirkarthi** [cdent/paste#40]
`base64.encodestring` raises `DeprecationWarning` and has been deprecated since Python 3.1 . `base64.encodebytes` can be used to fix the warning.

https://github.com/cdent/paste/blob/5a542da992618e30a508f7f03259f63cf2ee1ceb/paste/auth/cookie.py#L147

**Comment by cdent** [comment]
If you could provide a pull request for this one too, that would be great. Thanks.

**Comment by tirkarthi** [comment]
Sure, I will add a PR for the two issues I have created. Thanks.
