### ISSUE TITLE
gzip middleware adds a HTTP body when it shouldn't (e.g., HEAD requests)

### ISSUE THREAD

**Issue by jamadden** [cdent/paste#43]
The [HTTP specification says](https://tools.ietf.org/html/rfc7231#section-4.3.2):

> the server MUST NOT send a message body in the response (i.e., the response terminates at the end of the header section)

Even if the WSGI app is careful about this, the gzip middleware can violate this if the client is willing to accept gzip responses. This happens because simply opening the `GzipFile`, even if no bytes are written to it, will result in writing the gzip header. 

This is a problem because the spec doesn't say what happens if a server violates this MUST NOT clause. We've observed an upstream HAProxy 2 producing unexpected 502 errors to the originating client due to this (most likely in the presence of HTTP pipelining or keep-alive connections).

This can be produced easily. Given this python script, installed in a Python 3.x environment with Paste 3.2.5:
```python
# paste_test.py
from wsgiref.simple_server import make_server
from paste.gzipper import middleware

def app(environ, start_response):
    start_response('200 OK',
                   [('Content-Type', 'text/plain')])
    return []

gzipped = middleware(app)

with make_server('', 8080, gzipped) as httpd:
    httpd.serve_forever()
```

If we start it and make a request that *doesn't* allow a gzip response, we get back an empty body, and the server logs it as such:
```console
$ python /tmp/paste_test.py &
[1] 79887
$ echo -e 'HEAD / HTTP/1.0\r\nAccept-Encoding: identity\r\n\r\n' | socat TCP4:localhost:8080 -
HTTP/1.0 200 OK
Date: Fri, 10 Jan 2020 13:08:50 GMT
Server: WSGIServer/0.2 CPython/3.8.1
Content-Type: text/plain
Content-Length: 0

127.0.0.1 - - [10/Jan/2020 07:08:50] "HEAD / HTTP/1.0" 200 0
```

Now, if we allow a gzip response, we can see that we get 20 bytes of gibberish data:
```console
$ echo -e 'HEAD / HTTP/1.0\r\nAccept-Encoding: gzip\r\n\r\n' | socat TCP4:localhost:8080 -
HTTP/1.0 200 OK
Date: Fri, 10 Jan 2020 13:08:58 GMT
Server: WSGIServer/0.2 CPython/3.8.1
Content-Type: text/plain
content-encoding: gzip
Content-Length: 20

jw^�127.0.0.1 - - [10/Jan/2020 07:08:58] "HEAD / HTTP/1.0" 200 20
```

Which is exactly what you get simply opening and closing a `GzipFile`:
```pycon
>>> import io, gzip
>>> buf = io.BytesIO()
>>> f = gzip.GzipFile(mode='wb', fileobj=buf)
>>> buf.getvalue() # Header has already been written
b'\x1f\x8b\x08\x00%{\x18^\x02\xff'
>>> len(buf.getvalue())
10
>>> f.close()
None
>>> len(buf.getvalue()) # trailer has been added
20
```

I think a fix could be pretty simple, checking against the `REQUEST_METHOD`:
```diff
--- gzipper.py.orig	2020-01-10 07:10:16.406705538 -0600
+++ gzipper.py	2020-01-10 07:11:38.635141468 -0600
@@ -25,7 +25,8 @@
         self.compress_level = int(compress_level)

     def __call__(self, environ, start_response):
-        if 'gzip' not in environ.get('HTTP_ACCEPT_ENCODING', ''):
+        if 'gzip' not in environ.get('HTTP_ACCEPT_ENCODING', '') \
+           or environ['REQUEST_METHOD'] == 'HEAD':
             # nothing for us to do, so this middleware will
             # be a no-op:
             return self.application(environ, start_response)
```

I'm happy to work up a PR if desired.

**Comment by cdent** [comment]
Thank you very much for the really detailed explanation.

> I'm happy to work up a PR if desired.

Yeah, if you can that would be great. I'll merge it into a new release quickly.

Your fix looks correct to me. I'm surprised this hasn't come up before.

As I'm sure you're aware Paste is mostly dead. I'm keeping it on life support, accepting bug fixing pull requests, but that's about the extent of it.

Thanks

**Comment by jamadden** [comment]
> Yeah, if you can that would be great. I'll merge it into a new release quickly.

Thanks. #44 is open.

> I'm surprised this hasn't come up before.

It only recently became an issue for us when we updated to HAProxy 2; we didn't see it with HAProxy 1.
