### ISSUE TITLE
add ipv6 support

### ISSUE THREAD

**Issue by Lekinho** [cdent/paste#49]
Hi guys, 

I understand this is mostly in maintenance now, However , this is a fix that has been proposed and presented from the old repo, but at the time it wasnt being actively maintained.

Any objections? if so, what is the recommended path to adding said change?

Please see this link for background : https://bitbucket.org/ianb/paste/issues/18/add-ipv6-support

**Comment by cdent** [comment]
I'm happy to accept a pull request if you're able to provide one, especially if it include tests or you're able to point to it being "safe".

Based on the discussion on the original issue, it looks like it should be relatively straightforward.

**Comment by Lekinho** [comment]
Ok great, Yes i have been using a patched version of paste based on the code shared in the discussion.
I will work on a pull request and try adding some tests for it too.

Thanks

**Comment by Lekinho** [comment]
> I'm happy to accept a pull request if you're able to provide one, especially if it include tests or you're able to point to it being "safe".
> 
> Based on the discussion on the original issue, it looks like it should be relatively straightforward.

Just an update, i've got a commit/branch ready locally. Could i get write access to create the upstream branch "add_ipv6" based of off current master?

Thanks

**Comment by cdent** [comment]
> Could i get write access to create the upstream branch "add_ipv6" based of off current master?

The usual github process is to fork the repository to your own user, branch there, and then make a pull request. If you're used to a different process it can be a bit weird to get used to but works pretty well. Github has pretty good docs on it at: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests

**Comment by cdent** [comment]
Added in #50 

release at https://pypi.org/project/Paste/3.4.0/
