### ISSUE TITLE
RFE: is it possible to start making github releases?🤔

### ISSUE THREAD

**Issue by kloczek** [cdent/paste#81]
On create github release entry is created email notification to those whom have set in your repo the web UI Watch->Releases.
gh release can contain additional comments (li changelog) or additional assets like release tar balls (by default it contains only assets from git tag) however all those part are not obligatory.
In simplest variant gh release can be empty because subiekt of the sent email contains git tag name.

I'm asking because my automation process uses those email notifications by trying to make preliminary automated upgrades of building packages, which allows saving some time on maintaining packaging procedures.
Probably other people may be interested to be instantly informed about release new version as well.

Documentation and examples of generate gh releases:
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
https://cli.github.com/manual/gh_release_upload/
https://github.com/marketplace/actions/github-release
https://pgjones.dev/blog/trusted-plublishing-2023/
https://github.com/jbms/sphinx-immaterial/issues/281#issuecomment-1700933026
tox target to publish on pypi and make gh release https://github.com/jaraco/skeleton/blob/928e9a86d61d3a660948bcba7689f90216cc8243/tox.ini#L42-L58

**Comment by cdent** [comment]
If you're interested in adding a pull request that automates this, please feel free. I'd be happy to add that.

Otherwise I'll add it myself before the next release, but that may be some time.

**Comment by kloczek** [comment]
Issue is that in the repo workflows I don't see your release process 😋

**Comment by cdent** [comment]
Currently the release process is entirely manual:

1. update docs/news.txt
2. update version in setup.py
3. commit those changes
4. git tag a version
5. python setup.py sdist bdist_wheel
6. twine upload

The reasons for it remaining manual are basically:

1. laziness
2. an expectation (apparently incorrect!) that paste is legacy and nobody should be using it so why bother?
3. rarity of releases

**Comment by cdent** [comment]
> The reasons for it remaining manual are basically:

I mean the reasons it has been manual up to now. Changing it to be automatic would be great, but see point 1 (laziness)...

**Comment by cdent** [comment]
I have something in progress that will semi-automate this, enough that next time there is a release to pypi there will also be a release to GitHub.

**Comment by kloczek** [comment]
Thank you very much 👍 😄
